server:
  port: 8877
  thrift:
    host: localhost
    port: 9999

thrift:
  server:
    serverList:
      - appName: com.iyingdi.user
        host: localhost
        port: 9999
        interfaceList:
#          - com.iyingdi.user.thrift.UserThriftService
          - com.lupf.thriftapi.StudentService


#debug: true